theme: jekyll-theme-minimal
logo: /prof.png
title: Tony Lim
description: Welcome! Feel free to browse through the curated projects I've worked on during my time as a graduate student at the UCLA Fielding School of Public Health.

markdown: kramdown
