theme: jekyll-theme-minimal
title: Tony Lim
logo: tonylim96.github.io/me.png
description: Welcome! Feel free to browse through the curated projects I've worked on during my time as a graduate student at the UCLA Fielding School of Public Health.

markdown: kramdown
