theme: jekyll-theme-minimal
title: Tony Lim
tagline: Master of Public Health, Health Management
description: Welcome! Feel free to browse through the projects I've worked on during my time at the UCLA Fielding School of Public Health. 
